# Generated by Django 4.2.13 on 2024-08-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
        migrations.AlterModelOptions(
            name='privatmassage',
            options={'ordering': ['name']},
        ),
    ]
