# Generated by Django 4.2.13 on 2024-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_revrubric_alter_privatmassage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
