# Generated by Django 4.2.13 on 2024-08-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_rubricmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RubricManager',
        ),
    ]
