# Generated by Django 4.2.13 on 2024-08-21 09:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_delete_rubricmanager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bb',
            managers=[
                ('by_price', django.db.models.manager.Manager()),
            ],
        ),
    ]
