# Generated by Django 4.2.13 on 2024-08-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bb',
            managers=[
            ],
        ),
    ]
